=== vumilan/xml/country_fact_document.dtd
<!ELEMENT country_fact_document (country+)>

<!ELEMENT country (name, images, introduction, geography, society, economy)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT images (image+)>
<!ELEMENT introduction (paragraph+)>
<!ELEMENT geography (location, coordinates, map_references, area, climate, terrain, natural_resources)>
<!ELEMENT society (population, languages, religions, birth_rate, death_rate, population_distribution, literacy)>
<!ELEMENT economy (overview, gdp, debt, export, import)>

<!ELEMENT image (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT coordinates (#PCDATA)>
<!ELEMENT map_references (#PCDATA)>
<!ELEMENT area (a_total, land, water)>
<!ELEMENT climate (#PCDATA)>
<!ELEMENT terrain (#PCDATA)>
<!ELEMENT natural_resources (#PCDATA)>
<!ELEMENT population (#PCDATA)>
<!ELEMENT languages (language+)>
<!ELEMENT religions (#PCDATA)>
<!ELEMENT birth_rate (#PCDATA)>
<!ELEMENT death_rate (#PCDATA)>
<!ELEMENT population_distribution (#PCDATA)>
<!ELEMENT literacy (definition, total_population, male, female)>
<!ELEMENT overview (paragraph+)>
<!ELEMENT gdp (purchasing_power_parity, official_exchange_rate, real_growth_rate, per_capital, composition)>
<!ELEMENT debt (#PCDATA)>
<!ELEMENT export (total, partners, commodities)>
<!ELEMENT import (total, partners, commodities)>

<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT a_total (#PCDATA)>
<!ELEMENT land (#PCDATA)>
<!ELEMENT water (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT total_population (#PCDATA)>
<!ELEMENT male (#PCDATA)>
<!ELEMENT female (#PCDATA)>
<!ELEMENT purchasing_power_parity (#PCDATA)>
<!ELEMENT official_exchange_rate (#PCDATA)>
<!ELEMENT real_growth_rate (#PCDATA)>
<!ELEMENT per_capital (#PCDATA)>
<!ELEMENT composition (by_end_use, by_sector_of_origin)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT partners (#PCDATA)>
<!ELEMENT commodities (#PCDATA)>

<!ELEMENT by_end_use (household_consumption, government_consumption, investment_in_fixed_capital, investment_in_inventories, exports_of_goods_and_services, imports_of_goods_and_services)>
<!ELEMENT by_sector_of_origin (agriculture, industry, services)>

<!ELEMENT household_consumption (#PCDATA)>
<!ELEMENT government_consumption (#PCDATA)>
<!ELEMENT investment_in_fixed_capital (#PCDATA)>
<!ELEMENT investment_in_inventories (#PCDATA)>
<!ELEMENT exports_of_goods_and_services (#PCDATA)>
<!ELEMENT imports_of_goods_and_services (#PCDATA)>
<!ELEMENT agriculture (#PCDATA)>
<!ELEMENT industry (#PCDATA)>
<!ELEMENT services (#PCDATA)>

<!ATTLIST country_fact_document language CDATA #IMPLIED>
<!ATTLIST country id ID #REQUIRED>
<!ATTLIST area units CDATA #FIXED "sq km">
<!ATTLIST literacy units CDATA #FIXED "percentage">
<!ATTLIST purchasing_power_parity units (dollars|billion_dollars|trillion_dollars) "dollars">
<!ATTLIST official_exchange_rate units (dollars|billion_dollars|trillion_dollars) "dollars">
<!ATTLIST real_growth_rate units CDATA #FIXED "percentage">
<!ATTLIST per_capital units (dollars|billion_dollars|trillion_dollars) "dollars">
<!ATTLIST by_end_use units CDATA #FIXED "percentage">
<!ATTLIST by_sector_of_origin units CDATA #FIXED "percentage">
<!ATTLIST debt units (dollars|billion_dollars|trillion_dollars) "dollars">
<!ATTLIST total units (dollars|billion_dollars|trillion_dollars) "dollars">

=== vumilan/xml/country_fact_document.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE country_fact_document SYSTEM "country_fact_document.dtd">

<country_fact_document language="en">
    <!-- ======= single country ======= -->
    <country id="1">
        <name>Vietnam</name>
        <images>
          <image>01.jpg</image>
          <image>02.jpg</image>
          <image>03.jpg</image>
        </images>
        <introduction>
          <paragraph>The conquest of Vietnam by France began in 1858 and was completed by 1884. It became part of French Indochina in 1887. Vietnam declared independence after World War II, but France continued to rule until its 1954 defeat by communist forces under Ho Chi MINH. Under the Geneva Accords of 1954, Vietnam was divided into the communist North and anti-communist South. US economic and military aid to South Vietnam grew through the 1960s in an attempt to bolster the government, but US armed forces were withdrawn following a cease-fire agreement in 1973. Two years later, North Vietnamese forces overran the South reuniting the country under communist rule. Despite the return of peace, for over a decade the country experienced little economic growth because of conservative leadership policies, the persecution and mass exodus of individuals - many of them successful South Vietnamese merchants - and growing international isolation. However, since the enactment of Vietnam's "doi moi" (renovation) policy in 1986, Vietnamese authorities have committed to increased economic liberalization and enacted structural reforms needed to modernize the economy and to produce more competitive, export-driven industries. The communist leaders maintain tight control on political expression but have demonstrated some modest steps toward better protection of human rights. The country continues to experience small-scale protests, the vast majority connected to either land-use issues, calls for increased political space, or the lack of equitable mechanisms for resolving disputes. The small-scale protests in the urban areas are often organized by human rights activists, but many occur in rural areas and involve various ethnic minorities such as the Montagnards of the Central Highlands, Hmong in the Northwest Highlands, and the Khmer Krom in the southern delta region.</paragraph>
        </introduction>
        <geography>
          <location>Southeastern Asia, bordering the Gulf of Thailand, Gulf of Tonkin, and South China Sea, as well as China, Laos, and Cambodia</location>
          <coordinates>16 10 N, 107 50 E</coordinates>
          <map_references>Southeast Asia</map_references>
          <area units="sq km">
            <a_total>331210</a_total>
            <land>310070</land>
            <water>21140</water>
          </area>
          <climate>tropical in south; monsoonal in north with hot, rainy season (May to September) and warm, dry season (October to March)</climate>
          <terrain>low, flat delta in south and north; central highlands; hilly, mountainous in far north and northwest</terrain>
          <natural_resources>antimony, phosphates, coal, manganese, rare earth elements, bauxite, chromate, offshore oil and gas deposits, timber, hydropower, arable land</natural_resources>
        </geography>
        <society>
          <population>97040334</population>
          <languages>
            <language>Vietnamese</language>
            <language>English</language>
            <language>French</language>
            <language>Chinese</language>
          </languages>
          <religions>Buddhist 7.9%, Catholic 6.6%, Hoa Hao 1.7%, Cao Dai 0.9%, Protestant 0.9%, Muslim 0.1%, none 81.8%</religions>
          <birth_rate>15.2 births/1,000 population</birth_rate>
          <death_rate>5.9 deaths/1,000 population</death_rate>
          <population_distribution>though it has one of the highest population densities in the world, the population is not evenly dispersed; clustering is heaviest along the South China Sea and Gulf of Tonkin, with the Mekong Delta (in the south) and the Red River Valley (in the north) having the largest concentrations of people</population_distribution>
          <literacy units="percentage">
            <definition>age 15 and over can read and write</definition>
            <total_population>94.5</total_population>
            <male>96.3</male>
            <female>92.8</female>
          </literacy>
        </society>
        <economy>
          <overview>
            <paragraph>Vietnam is a densely populated developing country that has been transitioning since 1986 from the rigidities of a centrally planned, highly agrarian economy to a more industrial and market based economy, and it has raised incomes substantially. Vietnam exceeded its 2017 GDP growth target of 6.7% with growth of 6.8%, primarily due to unexpected increases in domestic demand, and strong manufacturing exports.</paragraph>
            <paragraph>Vietnam has a young population, stable political system, commitment to sustainable growth, relatively low inflation, stable currency, strong FDI inflows, and strong manufacturing sector. In addition, the country is committed to continuing its global economic integration. Vietnam joined the WTO in January 2007 and concluded several free trade agreements in 2015-16, including the EU-Vietnam Free Trade Agreement (which the EU has not yet ratified), the Korean Free Trade Agreement, and the Eurasian Economic Union Free Trade Agreement. In 2017, Vietnam successfully chaired the Asia-Pacific Economic Cooperation (APEC) Conference with its key priorities including inclusive growth, innovation, strengthening small and medium enterprises, food security, and climate change. Seeking to diversify its opportunities, Vietnam also signed the Comprehensive and Progressive Agreement for the Transpacific Partnership in 2018 and continued to pursue the Regional Comprehensive Economic Partnership.</paragraph>
            <paragraph>To continue its trajectory of strong economic growth, the government acknowledges the need to spark a ‘second wave’ of reforms, including reforming state-owned-enterprises, reducing red tape, increasing business sector transparency, reducing the level of non-performing loans in the banking sector, and increasing financial sector transparency. Vietnam’s public debt to GDP ratio is nearing the government mandated ceiling of 65%.</paragraph>
            <paragraph>In 2016, Vietnam cancelled its civilian nuclear energy development program, citing public concerns about safety and the high cost of the program; it faces growing pressure on energy infrastructure. Overall, the country’s infrastructure fails to meet the needs of an expanding middle class. Vietnam has demonstrated a commitment to sustainable growth over the last several years, but despite the recent speed-up in economic growth the government remains cautious about the risk of external shocks.</paragraph>
          </overview>
          <gdp>
            <purchasing_power_parity units="billion dollars">648.7</purchasing_power_parity>
            <official_exchange_rate units="billion dollars">220.4</official_exchange_rate>
            <real_growth_rate units="percentage">6.8</real_growth_rate>
            <per_capital units="dollars">6900</per_capital>
            <composition>
              <by_end_use units="percentage">
                <household_consumption>66.9</household_consumption>
                <government_consumption>6.5</government_consumption>
                <investment_in_fixed_capital>24.2</investment_in_fixed_capital>
                <investment_in_inventories>2.8</investment_in_inventories>
                <exports_of_goods_and_services>100</exports_of_goods_and_services>
                <imports_of_goods_and_services>-101</imports_of_goods_and_services>
              </by_end_use>
              <by_sector_of_origin units="percentage">
                <agriculture>15.3</agriculture>
                <industry>33.3</industry>
                <services>51.3</services>
              </by_sector_of_origin>
            </composition>
          </gdp>
          <debt units="billion dollars">96.58</debt>
          <export>
            <total units="billion dollars">214.1</e_total>
            <partners>US 20.1%, China 14.5%, Japan 8%, South Korea 6.8%</partners>
            <commodities>clothes, shoes, electronics, seafood, crude oil, rice, coffee, wooden products, machinery</commodities>
          </export>
          <import>
            <total units="billion dollars">202.6</i_total>
            <partners>China 25.8%, South Korea 20.5%, Japan 7.8%, Thailand 4.9%</partners>
            <commodities>machinery and equipment, petroleum products, steel products, raw materials for the clothing and shoe industries, electronics, plastics, automobiles</commodities>
          </import>
        </economy>
    </country>
    <!-- ======= single country end ======= -->

    <!-- ======= single country ======= -->
    <country id="2">
        <name>China</name>
        <images>
          <image>01.jpg</image>
          <image>02.jpg</image>
          <image>03.jpg</image>
        </images>
        <introduction>
